version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: tsushima-s
      POSTGRES_PASSWORD: tsushima-s
      POSTGRES_DB: todo1
    restart: always
    networks:
      - lesson
networks:
  lesson: